 # ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

 eureka:
     client:
         enabled: true
         healthcheck:
             enabled: true
         fetch-registry: true
         register-with-eureka: true
         instance-info-replication-interval-seconds: 10
         registry-fetch-interval-seconds: 10
     instance:
         appname: AlbedoBootCloudMicro
         instanceId: AlbedoBootCloudMicro:${spring.application.instance-id:${random.value}}
         lease-renewal-interval-in-seconds: 5
         lease-expiration-duration-in-seconds: 10
         status-page-url-path: ${management.endpoints.web.base-path}/info
         health-check-url-path: ${management.endpoints.web.base-path}/health
         metadata-map:
             zone: primary # This is needed for the load balancer
             profile: ${spring.profiles.active}
             version: ${info.project.version:}
             git-version: ${git.commit.id.describe:}
             git-commit: ${git.commit.id.abbrev:}
             git-branch: ${git.branch:}
 ribbon:
     eureka:
         enabled: true
 feign:
     hystrix:
         enabled: true
 #    client:
 #        config:
 #            default:
 #                connectTimeout: 5000
 #                readTimeout: 5000

 # See https://github.com/Netflix/Hystrix/wiki/Configuration
 hystrix:
     command:
         default:
             execution:
                 isolation:
                     strategy: SEMAPHORE
     # See https://github.com/spring-cloud/spring-cloud-netflix/issues/1330
     #                    thread:
     #                        timeoutInMilliseconds: 10000
     shareSecurityContext: true

 management:
     endpoints:
         web:
             base-path: /management
             exposure:
                 include: ["configprops", "env", "health", "info", "threaddump"]
     endpoint:
         health:
             show-details: when_authorized
     info:
         git:
             mode: full
     health:
         mail:
             enabled: false # When using the MailService, configure an SMTP server and set this to true
     metrics:
         enabled: false # http://micrometer.io/ is disabled by default, as we use http://metrics.dropwizard.io/ instead
spring:
    application:
        name: AlbedoBootCloudMicro
    mvc:
        favicon:
            enabled: false
#    resources:
#        add-mappings: false
    profiles:
        # The commented value for `active` can be replaced with valid spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # ${spring.profiles.active}
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: #spring.profiles.active#
    jackson:
        serialization.write_dates_as_timestamps: false
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    messages:
        basename: i18n/messages
#    thymeleaf:
#        mode: XHTML
server:
    servlet:
        session:
            cookie:
                http-only: true
 # Properties to be exposed on the /info management endpoint
info:
    # Comma separated list of profiles that will trigger the ribbon to show
    display-ribbon-on-profiles: "dev"
# ===================================================================
# Albedo specific properties
# ===================================================================

albedo:
    application: albedo
    adminPath: /api
    micorservice: albedobootcloudmicro
    microModel: true
    frontPath: /f
    defaultView: /swagger-ui/index.html
    staticFileDirectory: D:/temp/files/
    urlSuffix: html
    cluster: true
    quartzEnabled: true
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
    #cors: #By default CORS are not enabled. Uncomment to enable.
        #allowed-origins: "*"
        #allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        #allowed-headers: "*"
        #exposed-headers:
        #allow-credentials: true
        #max-age: 1800
    mail:
        from: AlbedoBootCloudMicro@localhost
    swagger:
        default-include-pattern: ${albedo.adminPath}/.*
        title: AlbedoBootCloudMicro API
        description: AlbedoBootCloudMicro API documentation
        version: 0.0.1
        terms-of-service-url:
        contact-name:
        contact-url:
        contact-email:
        license:
        license-url:
    ribbon:
        # comma seperated list of profiles to show a ribbon on the GUI
        displayOnActiveProfiles: dev
    http:
        restful: false
