 # ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
    client:
        enabled: true
        healthcheck:
            enabled: true
        fetch-registry: true
        register-with-eureka: true
        instance-info-replication-interval-seconds: 10
        registry-fetch-interval-seconds: 10
    instance:
        appname: albedoBootCloudGateway
        instanceId: albedoBootCloudGateway:${spring.application.instance-id:${random.value}}
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 10
        status-page-url-path: ${management.context-path}/info
        health-check-url-path: ${management.context-path}/health
        metadata-map:
            zone: primary # This is needed for the load balancer
            profile: ${spring.profiles.active}
            version: ${info.project.version}
ribbon:
    eureka:
        enabled: true
# See http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html
zuul: # those values must be configured depending on the application specific needs
    host:
        max-total-connections: 1000
        max-per-route-connections: 100
    semaphore:
        max-semaphores: 500

# See https://github.com/Netflix/Hystrix/wiki/Configuration
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 10000

management:
    security:
        roles: ADMIN
    context-path: /management
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true # When using the MailService, configure an SMTP server and set this to true
spring:
    application:
        name: albedoBootCloudGateway
    mvc:
        throw-exception-if-no-handler-found: true
#    resources:
#        add-mappings: false
    profiles:
        # The commented value for `active` can be replaced with valid spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # ${spring.profiles.active}
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: #spring.profiles.active#
    jackson:
        serialization.write_dates_as_timestamps: false
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming:
                strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    messages:
        basename: i18n/messages
#    thymeleaf:
#        mode: XHTML
    web:
        root:
            prefix:

server:
    session:
        cookie:
            http-only: true

info:
    project:
        version: #project.version#


security:
    basic:
        enabled: false

#mybaits-plus配置，修改主键类型，mapper.xml、type 别名等
mybatis-plus:
  mapper-locations: classpath*:/mappings/modules/*/*Mapper.xml
  typeAliasesPackage: com.albedo.java.modules.*.domain
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    logic-delete-value: -2
    logic-not-delete-value: 0
    #数据库大写下划线转换
    #capital-mode: true
#    meta-object-handler: com.albedo.java.common.persistence.handler.EntityMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

# ===================================================================
# Albedo specific properties
# ===================================================================

albedo:
    application: albedoBootCloudGateway
    adminPath: /api
    frontPath: /f
    gatewayModel: true
    defaultView:
    staticFileDirectory: D:/temp/files/
    urlSuffix: html
    cluster: true
    quartzEnabled: true
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    #cors: #By default CORS are not enabled. Uncomment to enable.
        #allowed-origins: "*"
        #allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        #allowed-headers: "*"
        #exposed-headers:
        #allow-credentials: true
        #max-age: 1800
    mail:
        from: albedoBootCloudGateway@localhost
    swagger:
        default-include-pattern: ${albedo.adminPath}/.*
        title: albedoBootCloudGateway API
        description: albedoBootCloudGateway API documentation
        version: 0.0.1
        terms-of-service-url:
        contact-name:
        contact-url:
        contact-email:
        license:
        license-url:
    ribbon:
        # comma seperated list of profiles to show a ribbon on the GUI
        displayOnActiveProfiles: dev
    http:
        restful: false
